### ISSUE TITLE
Kiali integration

### ISSUE THREAD

**Issue by DanoThom** [solo-io/service-mesh-hub#480]
More of a question really: any chance of adding a `--kiali` flag to the supergloo install in the CLI? Would be great to have some native kiali integration in the workflow seeing as it plays so well with all of the other observability components.

**Comment by ilackarms** [comment]
@DanoThom it's totally doable, but something we skipped for the time being. if you feel comfortable enough, we'd happily review / assist with a PR to add it to supergloo.

seeing as how kiali is a part of the istio helm chart, it should be easy to enable just as the istio ingress/egress was in this PR: https://github.com/solo-io/supergloo/pull/404

i may have misunderstood though, i'm assuming you meant to install istio with kiali (rather than SuperGloo with its own kiali). we could do Kiali, but i believe right now kiali only supports istio (which diverges a bit from sg's mesh-agnostic approach)

**Comment by DanoThom** [comment]
@ilackarms Ok great, doesn't sound too difficult to enable then. Unfortunately I doubt my Go-fu is up to scratch for anything meaningful though! And no, you totally understood - enabling the istio install with kiali is what I was inquiring about. Any chance we could add it as an 'Up for grabs' task?

**Comment by ilackarms** [comment]
@DanoThom certainly! i've added a `help-wanted` label to get some community attention on this issue

in the meantime, you could consider installing istio via the helm chart and using [supergloo discovery](https://supergloo.solo.io/mesh/mesh-discovery/) to detect istio once it's installed

**Comment by GrahamGoudeau** [comment]
Outdated issue- the product has changed significantly. Kiali support is still on Service Mesh Hub's roadmap, but not sure when we'll get to it.
